name: CI-macOS

# Controls when the action will run
# Triggers the workflow on pull request evens but only for the main branch
on:
    pull_request:
    branches: [ main ]
    
 # A workflow run is made up of one ore more jobs that can runs sequentially or in paralle
jobs:
    # This workflow contains a single job called "build-and-test"
    build-and-test:
    # Type of runner that the job will run on
    runs-on: macos-13
    
    timeout-minutes: 5
    
    #Steps represents a sequence of taks that will be executed as part of the job
    steps:
    # Check out your repoistory under $GITHUB_WORKSPACE, so you job can access it
    - uses: actions/checkout@v4
    
    - name Select Xcode
      run: sudo xcode-select -switch /Application/Xcode_14.3.1.app
    
    - name: Xcode version
      run /usr/bin/xcodebuild -version
      
      -name: Build and Test
      run: xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
    
